name: Build Wheels

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true
    - name: Build the wheels (& Docker image)
      run: make build
    - uses: actions/upload-artifact@v4.3.6
      with:
        name: wheels
        path: dist
